DROP SEQUENCE BOARD_SEQ;
DROP SEQUENCE MEMBER_SEQ;

DROP TABLE BOARD;
DROP TABLE MEMBER;

CREATE TABLE MEMBER (
	MNO NUMBER PRIMARY KEY,
	MID VARCHAR2(30) NOT NULL UNIQUE,
	MPW VARCHAR2(30) NOT NULL,
	MNAME VARCHAR2(30) NOT NULL,
	MEMAIL VARCHAR2(200) NOT NULL UNIQUE,
	MPHONE VARCHAR2(20) NOT NULL UNIQUE,
	MADDRESS VARCHAR2(200),
	MREGDATE DATE
);

CREATE TABLE BOARD(
	BNO NUMBER PRIMARY KEY,
	MID VARCHAR2(30) REFERENCES MEMBER (MID),
	BTITLE VARCHAR2(1000) NOT NULL,
	BCONTENT VARCHAR2(4000),
	BFILENAME VARCHAR2(300),
	BIP VARCHAR2(30),
	BHIT NUMBER,
	BLASTMODIFY DATE,	-- 최종 수정일
	BREGDATE DATE, 		-- 최초 작성일
	BDELETE NUMBER,		-- 삭제여부 (삭제 : -1, 정상: 0)
	BGROUP NUMBER,		-- 게시글 그룹 (어떤 게시글 과 그 게시글에 달린 댓글들은 모두 같은 그룹)
	BGROUPORD NUMBER,	-- 게시글 순서 (같은 그룹에서 표시할 순서) 
	BDEPTH NUMBER		-- 게시글/댓글 구분 용도 (게시글 : 0, 댓글: 1이상)
);

CREATE SEQUENCE MEMBER_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 999999 NOCYCLE NOCACHE;
CREATE SEQUENCE BOARD_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 999999 NOCYCLE NOCACHE;

SELECT * FROM BOARD;
